### ISSUE TITLE
Week 2: 2024-11-25 to 2024-12-01

### ISSUE THREAD

**Issue by jenson-chang** [UBC-MDS/academic-success-prediction#10]
2024-11-20 Lab:
Create Docker file and create Github workflow
- [x] Updated environment.yaml (@MCatherine1994 )
- [x] Conda-lock file (@MCatherine1994)
- [x] Dockerfile (@MCatherine1994 )
- [x] Github actions workflow (@siddart-1 )
- [x] Update README document with Docker instructions (@jenson-chang )

2024-11-21 Meetup:
- [x] Data validation check 1-8 (@jyflowang)
- [x] Data validation check 9 (@siddart-1)
- [x] Data validation check 10-11 (@jenson-chang)

2024-11-22 Online meetup:

**Comment by MCatherine1994** [comment]
Todo for week 2 submission:
- [ ] Regenerate pdf file
- [ ] Create Github release 1.0.0
- [ ] Create pdf for submission
