### ISSUE TITLE
Can't run remote docker image

### ISSUE THREAD

**Issue by jenson-chang** [UBC-MDS/academic-success-prediction#12]
I'm having issues running the image with the following command. 

`docker run --rm -p 8787:8787 siddart/mds:a2c0482`

I see the jupyterlab running in the terminal but I can't access it via `http://localhost:8787`. Can someone try the remote image and see if they see the same issue?

**Comment by MCatherine1994** [comment]
We could run `docker run --rm -p 8787:8888 siddart/mds:a2c0482` this works. 

so the 8888 is the remote port that we shouldn't change, and 8787 will be our local port, so we access by http://127.0.0.1:8787/lab

**Comment by jenson-chang** [comment]
Confirmed it's a misconfiguration issue.
